// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bciqrcfioxfvdfxkqdzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjaXFyY2Zpb3hmdmRmeGtxZHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDM4MTQsImV4cCI6MjA2MzQxOTgxNH0.7R6tBLC2m1vqblRrndX2sUBZNEc4Hl-NvcDuNr8q9gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);